keys:
  - &home_stefan age1h08pk2dk8x6rvrdqyke85tcfy6s5n0vxpjausn6a968tsa2xae5shc5qec
creation_rules:
  - path_regex: common/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *home_stefan
  - path_regex: home/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *home_stefan
